name: ci

on:
  push:
    branches: [main, develop, feat/** , fix/** , release/**]
  pull_request:
    branches: [main, develop]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: /opt/flutter
          key: flutter-linux-3.27.x
      - name: Install Flutter
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.27.0-stable.tar.xz | tar -xJ -C /opt
      - run: echo "/opt/flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
      - run: flutter analyze lib

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: /opt/flutter
          key: flutter-linux-3.27.x
      - name: Install Flutter
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.27.0-stable.tar.xz | tar -xJ -C /opt
      - run: echo "/opt/flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
      - run: flutter test
